### ISSUE TITLE
[Regression] Error: No "update_submodules" targets found.

### ISSUE THREAD

**Issue by Krinkle** [jaubourg/grunt-update-submodules#7]
Upgrading from v0.3.0 to v0.4.1 I get this error on projects where a plain `update_submodules` task is used.

``` js
module.exports = function (grunt) {
    grunt.loadNpmTasks('grunt-update-submodules');
    // ..

    grunt.initConfig({
        // ..
    });

    grunt.registerTask('build', ['update_submodules', /* .. */ ]);
    grunt.registerTask('default', 'build');
};
```

I guess that's because it's a multi task now so the default invocation with no targets configured in `initConfig` no longer works. I'll stick to version v0.3.0 for now, but just wondering if this is intentional, or whether this should still work.

**Comment by jaubourg** [comment]
Happened [here](https://github.com/jaubourg/grunt-update-submodules/commit/9cbb3088bad374b00367ecf22e80e28f9703b504). I'd say it's an unfortunate regression but I haven't worked on this in a loooong time and have forgotten everything about making a grunt plugin... so hell if I know if this is to be expected or can be remedied.

**Comment by Krinkle** [comment]
Okay, no worries. In the few cases where I need this I can do it manually. And in most cases where this plugin is used, it's probably leftover boilerplate. Can easily do without. Thanks :)
